is_train: True
test_model_path: None
embed_units: 300
symbols: 30000
units: 512
layers: 2
batch_size: 5
data_dir: "../../data"
num_epoch: 20
lr_rate: 0.0001
lstm_dropout: 0.3
linear_dropout: 0.2
max_gradient_norm: 5
trans_units: 100
gnn_layers: 3
gat_head_num: 1
fact_dropout: 0.0
fact_scale: 1
beam_search_width: 200
max_hop: 2
max_candidate_size: 50
result_dir_name: "./result1.txt"
model_save_name: "./model"
generated_text_name: "./generated_text"
log_dir: "./log1.txt"
tensorboard_path: "../test"
to_generate: False
decode: False