is_train: True
test_model_path: None
embed_units: 300
symbols: 30000
units: 512
layers: 2
batch_size: 5
data_dir: "../ConceptFlow/data/data"
num_epoch: 20
lr_rate: 0.0001
lstm_dropout: 0.3
linear_dropout: 0.2
max_gradient_norm: 5
trans_units: 100
gnn_layers: 3
fact_dropout: 0.0
fact_scale: 1
pagerank_lambda: 0.8
beam_search_width: 20
max_hop: 2
result_dir_name: "result.txt"
model_save_name: "model"
generated_text_name: "generated_text"
log_dir: "log.txt"
tensorboard_path: "./bs_v1"